### ISSUE TITLE
Error running the HelloWorld example

### ISSUE THREAD

**Issue by implicit-invocation** [klaus7/jfastnet#2]
```
2018-09-13 11:44:20 ERROR KryoSerialiser:87 - Couldn't stream from byte array.
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): com.jfastnet.messages.ConnectResponse
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1310)
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1127)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1136)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:559)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:535)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at com.jfastnet.serialiser.KryoSerialiser.deserialise(KryoSerialiser.java:81)
	at com.jfastnet.peers.javanet.JavaNetPeer.receive(JavaNetPeer.java:128)
	at com.jfastnet.peers.javanet.JavaNetPeer$MessageReceivingRunnable.run(JavaNetPeer.java:181)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by klaus7** [comment]
Interesting, thanks! I identified that it was working correctly with Kryo 3.0.0, but not with Kryo 4.0.0 - will look into it.

**Comment by klaus7** [comment]
It was because of this commit: https://github.com/EsotericSoftware/kryo/commit/bfc02befd7f479165cf86fc7c8b22b75c2ff35ca

And I didn't notice, because I configure all my kryo objects like this in my projects:
`kryo.setInstantiatorStrategy(new DefaultInstantiatorStrategy(new StdInstantiatorStrategy())); `

This way, you don't require a no-arg constructor. Thanks for sharing the issue! :)
